
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define CPU_MIMXRT1062DVL6A
#define DATA_SECTION_IS_CACHEABLE 1
#define EVK_MCIMXRM
#define FSL_SDK_DRIVER_QUICK_ACCESS_ENABLE 1
#define FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL 1
#define HAVE_CCONFIG_H
#define RT_USING_LIBC
#define RT_USING_NEWLIB
#define SKIP_SYSCLK_INIT
#define XIP_BOOT_HEADER_DCD_ENABLE 1
#define XIP_BOOT_HEADER_ENABLE 1
#define XIP_EXTERNAL_FLASH 1
#define _POSIX_C_SOURCE 1
#define __RTTHREAD__
#define __START entry

#endif /*RTCONFIG_PREINC_H__*/
